collections:
  - name: "home"
    label: "Startseite"
    files:
      - file: "content/home.md"
        label: "Startseite"
        name: "home"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Untertitel", name: "subtitle", widget: "string" }
          - { label: "Text", name: "body", widget: "markdown" }
